---
- name: 'Install dependencies'
  tags: 'mongodb'
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update_cache=yes
  with_items:
    - 'python-pycurl' # Required by Ansible for adding apt repositories

- name: 'Add MongoDB apt key'
  tags: 'mongodb'
  sudo: 'yes'
  apt_key: >
    url=http://docs.mongodb.org/10gen-gpg-key.asc
    state=present

- name: 'Add MongoDB apt repository'
  tags: 'mongodb'
  sudo: 'yes'
  apt_repository: >
    repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
    state=present

- name: 'Install MongoDB'
  tags: 'mongodb'
  sudo: 'yes'
  apt: >
    pkg=mongodb-org
    state=present
    update_cache=true

- name: 'Ensure backup script directory exists'
  tags: 'mongodb'
  sudo: 'yes'
  file: >
    path={{ mongodb_backup_script_dir }}
    state=directory
    owner=root
    group=backup

- name: 'Install backup script'
  tags: 'mongodb'
  sudo: 'yes'
  template: >
    src=mongo_dump.sh.j2
    dest={{ mongodb_backup_script_dir }}/{{ mongodb_backup_script_filename }}
    owner=root
    group=backup

- name: 'Set up cron job for automated backups'
  tags: 'mongodb'
  sudo: 'yes'
  cron: >
    name="{{ mongodb_backup_cron_name }}"
    special_time={{ mongodb_backup_frequency }}
    job="sh {{ mongodb_backup_script_dir }}/{{ mongodb_backup_script_filename }}"
